spring.application.name=paymentservice
server.port=8084

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
#spring.mongodb.uri=mongodb://localhost:27017/payments_db

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

springdoc.swagger-ui.enabled=true