spring.application.name=paymentservice
server.port=8084

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

springdoc.swagger-ui.enabled=true
management.endpoints.web.exposure.include=health

