spring.application.name=paymentservice
server.port=8084

spring.mongodb.uri=mongodb://localhost:27017/payments_db

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true